name: Automated Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image and container
        run: |
          cd dockerfile
          docker build -t ml:latest .
          docker run -d -p 5000:5000 ml