name: learn-github-actions
on:
  push:
    branches: [ $default-branch ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image and container
        run: cd dockerfile
        run: docker build -t ml:latest .
        run: docker run -d -p 5000:5000 ml