name: learn-github-actions
on:
  push:
    branches: [ $default-branch ]
jobs:
  automated-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image and container
        run: cd dockerfile
             docker build -t ml:latest .  
             docker run -d -p 5000:5000 ml
      # - name: Run tests
      #   run: 